id: IA40F6789
legacy_id: P001774
ocr_import_info:
  bdrc_scan_id: W1KG11822
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T14:45:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:08:46.898112+00:00'
last_modified: 2022-08-31 11:09:26.226736
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11822
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11822
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་མཐའི་རྣམ་བཞག་འཁྲུལ་སྤོང་གདོང་ལྔའི་སྒྲ་དབྱངས་དང་དེའི་འགྲེལ་པ་ཀུན་བཟང་ཞིང་གི་ཉི་མ།
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.7974713740166124
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I1KG11828:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11828
      total_pages: 680
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11828.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.7974713740166124
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
