id: IA40F6789
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T14:50:31+00:00'
last_modified: '2022-06-07T15:06:19.909707+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11822
  title: གྲུབ་མཐའི་རྣམ་བཞག་འཁྲུལ་སྤོང་གདོང་ལྔའི་སྒྲ་དབྱངས་དང་དེའི་འགྲེལ་པ་ཀུན་བཟང་ཞིང་གི་ཉི་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4390':
      image_group_id: I1KG11828
      title: ''
      total_pages: 680
      order: 1
      base_file: 4390.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
