id: P001774
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11822
  title: གྲུབ་མཐའི་རྣམ་བཞག་འཁྲུལ་སྤོང་གདོང་ལྔའི་སྒྲ་དབྱངས་དང་དེའི་འགྲེལ་པ་ཀུན་བཟང་ཞིང་གི་ཉི་མ།
  author: ''
  volumes:
    91479db49989480eb42f0f802ab180fb:
      image_group_id: I1KG11828
      title: ''
      volume_number: 1
      total_pages: 680
