id: opecha:P001774
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11822
  title: གྲུབ་མཐའི་རྣམ་བཞག་འཁྲུལ་སྤོང་གདོང་ལྔའི་སྒྲ་དབྱངས་དང་དེའི་འགྲེལ་པ་ཀུན་བཟང་ཞིང་གི་ཉི་མ།
  volume: ''
  author: ''
